---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc37 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc37 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -laR *
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc37 arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc37 arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -laR *
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc36 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc36 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -laR *
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc36 arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc36 arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -laR *
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc36 armv7 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc36 armv7 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -laR *
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc35 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc35 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -laR *
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc35 arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc35 arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -laR *
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc35 armv7 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc35 armv7 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -laR *
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
