---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el9 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el9 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el8 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el8 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el7 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el7 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc37 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc37 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc36 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc36 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc35 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc35 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc34 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc34 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: amzn2 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh amzn2 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: jammy amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh jammy amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: focal amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh focal amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: bionic amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh bionic amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: xenial amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh xenial amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: trusty amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh trusty amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: bookworm amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh bookworm amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: bullseye amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh bullseye amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: buster amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh buster amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: stretch amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh stretch amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: jessie amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh jessie amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
type: docker
